# Cloudflare Pages configuration
# https://developers.cloudflare.com/pages/platform/build-configuration

# We need to specify this for Pages to recognize the file
pages_build_output_dir = "dist"

[build]
command = "npm i -g pnpm@10.8.1 && pnpm install && pnpm run build"

[build.environment]
NODE_VERSION = "23.11.0"
